// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetLoginDevicesReq struct {
}

type GetLoginDevicesResp struct {
	Devices []string `json:"devices"`
}

type KickDeviceReq struct {
	TargetDeviceType string `json:"targetDeviceType"`
}

type KickDeviceResp struct {
	Success bool `json:"success"`
}

type LoginReq struct {
	Phone      string `json:"phone"`
	Password   string `json:"password"`
	DeviceType string `json:"deviceType"`
	DeviceName string `json:"deviceName"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Success int32 `json:"success"`
}

type RegisterReq struct {
	Phone      string `json:"phone"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Sex        byte   `json:"sex"`
	Avatar     string `json:"avatar"`
	DeviceType string `json:"deviceType"`
	DeviceName string `json:"deviceName"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type UserFindReq struct {
	Phone string `json:"phone,optional"`
	Id    string `json:"id,optional"`
}

type UserFindResp struct {
	User *User `json:"user,omitempty"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Info       User   `json:"info"`
	DeviceType string `json:"deviceType"`
	DeviceId   string `json:"deviceId"`
}
