FROM alpine:3.18

# 添加时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.15/main\nhttps://mirrors.aliyun.com/alpine/v3.15/community" > /etc/apk/repositories && \
    apk update &&\
    apk --no-cache add tzdata iputils && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone

ENV TZ=Asia/Shanghai

# 安装 Go
ENV GOLANG_VERSION=1.23.0
ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV GOPROXY=https://goproxy.cn,direct

RUN apk add --no-cache \
    ca-certificates \
    gcc \
    g++ \
    make \
    git && \
    wget https://mirrors.aliyun.com/golang/go${GOLANG_VERSION}.linux-arm64.tar.gz && \
    tar -C /usr/local -xzf go${GOLANG_VERSION}.linux-amd64.tar.gz && \
    rm go${GOLANG_VERSION}.linux-arm64.tar.gz

# 验证安装
RUN go version

# 创建工作目录
WORKDIR /easy-chat

# 设置启动命令
CMD ["ping", "baidu.com"]