// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FriendDeleteReq struct {
	FriendUid string `json:"friend_uid"`
}

type FriendDeleteResp struct {
}

type FriendListReq struct {
}

type FriendListResp struct {
	List []*Friends `json:"list"`
}

type FriendPutInHandleReq struct {
	FriendReqId  int32  `json:"friend_req_id,omitempty"`
	HandleResult int32  `json:"handle_result,omitempty"` // 处理结果
	Remark       string `json:"remark,optional"`
}

type FriendPutInHandleResp struct {
}

type FriendPutInListReq struct {
	Direction int32 `json:"direction,optional"` // 1=收到的(别人加我 user_id=我) 2=我发出的(我加别人 req_uid=我) 默认1
}

type FriendPutInListResp struct {
	List []*FriendRequestView `json:"list"`
}

type FriendPutInReq struct {
	ReqMsg  string `json:"req_msg,omitempty"`
	ReqTime int64  `json:"req_time,omitempty"`
	UserId  string `json:"user_uid"`
}

type FriendPutInResp struct {
}

type MutualFriendCountReq struct {
	OtherId string `json:"other_id"`
}

type MutualFriendCountResp struct {
	Count int64 `json:"count"`
}
