// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FriendListReq struct {
}

type FriendListResp struct {
	List []*Friends `json:"list"`
}

type FriendPutInHandleReq struct {
	FriendReqId  int32 `json:"friend_req_id,omitempty"`
	HandleResult int32 `json:"handle_result,omitempty"` // 处理结果
}

type FriendPutInHandleResp struct {
}

type FriendPutInListReq struct {
}

type FriendPutInListResp struct {
	List []*FriendRequests `json:"list"`
}

type FriendPutInReq struct {
	ReqMsg  string `json:"req_msg,omitempty"`
	ReqTime int64  `json:"req_time,omitempty"`
	UserId  string `json:"user_uid"`
}

type FriendPutInResp struct {
}
