// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GroupCreateReq struct {
	Name string `json:"name,omitempty"`
	Icon string `json:"icon,omitempty"`
}

type GroupCreateResp struct {
}

type GroupListRep struct {
}

type GroupListResp struct {
	List []*Groups `json:"list,omitempty"`
}

type GroupPutInHandleRep struct {
	GroupReqId   int32  `json:"group_req_id,omitempty"`
	GroupId      string `json:"group_id,omitempty"`
	HandleResult int32  `json:"handle_result,omitempty"` // 处理结果
}

type GroupPutInHandleResp struct {
}

type GroupPutInListRep struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupPutInListResp struct {
	List []*GroupRequests `json:"list,omitempty"`
}

type GroupPutInRep struct {
	GroupId    string `json:"group_id,omitempty"`
	ReqMsg     string `json:"req_msg,omitempty"`
	ReqTime    int64  `json:"req_time,omitempty"`
	JoinSource int64  `json:"join_source,omitempty"`
}

type GroupPutInResp struct {
}

type GroupUserListReq struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupUserListResp struct {
	List []*GroupMembers `json:"List,omitempty"`
}
