// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GroupCreateReq struct {
	Name string `json:"name,omitempty"`
	Icon string `json:"icon,omitempty"`
}

type GroupCreateResp struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupListRep struct {
}

type GroupListResp struct {
	List []*Groups `json:"list,omitempty"`
}

type GroupPutInHandleRep struct {
	GroupReqId   int32  `json:"group_req_id,omitempty"`
	GroupId      string `json:"group_id,omitempty"`
	HandleResult int32  `json:"handle_result,omitempty"` // 处理结果
}

type GroupPutInHandleResp struct {
}

type GroupPutInListRep struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupPutInListResp struct {
	List []*GroupRequests `json:"list,omitempty"`
}

type GroupPutInRep struct {
	GroupId    string `json:"group_id,omitempty"`
	ReqMsg     string `json:"req_msg,omitempty"`
	ReqTime    int64  `json:"req_time,omitempty"`
	JoinSource int64  `json:"join_source,omitempty"`
	InviterUid string `json:"inviter_uid,optional"` // 邀请入群时必填
}

type GroupPutInResp struct {
}

type GroupUpdateReq struct {
	GroupId    string   `json:"group_id"`           // 必填
	Name       string   `json:"name,optional"`      // 可选
	Icon       string   `json:"icon,optional"`      // 可选
	IsVerify   bool     `json:"is_verify,optional"` // 可选
	UpdateMask []string `json:"update_mask"`        // 必填：要更新的字段列表，如 ["name","icon","is_verify"]
}

type GroupUpdateResp struct {
}

type GroupUserListReq struct {
	GroupId string `json:"group_id,omitempty"`
}

type GroupUserListResp struct {
	List []*GroupMembers `json:"List,omitempty"`
}

type MyCreatedGroupsReq struct {
}

type MyCreatedGroupsResp struct {
	List []*Groups `json:"list,omitempty"`
}
