// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FriendRequests struct {
	Id           int64  `json:"id,omitempty"`
	UserId       string `json:"user_id,omitempty"`
	ReqUid       string `json:"req_uid,omitempty"`
	ReqMsg       string `json:"req_msg,omitempty"`
	ReqTime      int64  `json:"req_time,omitempty"`
	HandleResult int    `json:"handle_result,omitempty"`
	HandleMsg    string `json:"handle_msg,omitempty"`
}

type Friends struct {
	Id        int32  `json:"id,omitempty"`
	FriendUid string `json:"friend_uid,omitempty"`
	Nickname  string `json:"nickname,omitempty"`
	Avatar    string `json:"avatar,omitempty"`
	Remark    string `json:"remark,omitempty"`
}

type GroupMembers struct {
	Id            int64  `json:"id,omitempty"`
	GroupId       string `json:"group_id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	Nickname      string `json:"nickname,omitempty"`
	UserAvatarUrl string `json:"user_avatar_url,omitempty"`
	RoleLevel     int    `json:"role_level,omitempty"`
	InviterUid    string `json:"inviter_uid,omitempty"`
	OperatorUid   string `json:"operator_uid,omitempty"`
}

type GroupRequests struct {
	Id            int64  `json:"id,omitempty"`
	UserId        string `json:"user_id,omitempty"`
	GroupId       string `json:"group_id,omitempty"`
	ReqMsg        string `json:"req_msg,omitempty"`
	ReqTime       int64  `json:"req_time,omitempty"`
	JoinSource    int64  `json:"join_source,omitempty"`
	InviterUserId string `json:"inviter_user_id,omitempty"`
	HandleUserId  string `json:"handle_user_id,omitempty"`
	HandleTime    int64  `json:"handle_time,omitempty"`
	HandleResult  int64  `json:"handle_result,omitempty"`
}

type Groups struct {
	Id              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	Icon            string `json:"icon,omitempty"`
	Status          int64  `json:"status,omitempty"`
	GroupType       int64  `json:"group_type,omitempty"`
	IsVerify        bool   `json:"is_verify,omitempty"`
	Notification    string `json:"notification,omitempty"`
	NotificationUid string `json:"notification_uid,omitempty"`
	CreatedAt       int64  `json:"created_at,omitempty"`
}
